// memory-store/tests/setup-integration.test.ts
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdirSync, rmSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { defaultConfig, validateConfig, parseSchedule, type GreatMindsConfig } from '../src/config-schema.js';

// ── Helpers ───────────────────────────────────────────────────────────────

function generateStatusMd(config: GreatMindsConfig): string {
  const agentRows = config.agents.active.length > 0
    ? config.agents.active.map(a => `| ${a} | Active | — |`).join('\n')
    : '| — | — | No agents configured yet |';

  const scheduleNote = config.pipeline.schedule === null
    ? '- **pipeline**: manual only'
    : `- **pipeline**: ${config.pipeline.schedule}`;

  return `# Great Minds Agency — Status

## Current State
- **state**: idle
- **project**: ${config.project}
- **last updated**: ${config.createdAt}
${scheduleNote}

## Active Agents

| Agent | Status | Activity |
|-------|--------|----------|
${agentRows}

## PRD Directory
- ${config.prds.dir}
`;
}

function generateScoreboardMd(config: GreatMindsConfig): string {
  return `# Great Minds Agency — Scoreboard

**Project**: ${config.project}
**Session started**: ${config.createdAt.slice(0, 10)}
**Last updated**: ${config.createdAt.slice(0, 10)}

---

## Agency Totals

| Metric | Count |
|--------|-------|
| Commits | 0 |
| PRs merged | 0 |
| QA reports | 0 |
| Board reviews | 0 |

## Agent Scores

_(Updated as work progresses)_
`;
}

function generateTasksMd(config: GreatMindsConfig): string {
  return `# Great Minds Agency — Master Task Board

**Project**: ${config.project}
**Managed by**: Phil Jackson (Orchestrator)
**Last updated**: ${config.createdAt.slice(0, 10)}

## Open Tasks

_(No tasks yet — run /agency-plan to generate the first task list)_

## Recently Completed

_(none)_

## Blocked

_(none)_
`;
}

function generateCronScript(config: GreatMindsConfig, projectDir: string): string | null {
  if (config.pipeline.schedule === null) return null;
  return `#!/bin/bash
# Great Minds Agency — Pipeline Runner
# Schedule: ${config.pipeline.schedule}
# Project: ${config.project}
# Generated by /agency-setup on ${config.createdAt.slice(0, 10)}

set -euo pipefail

PROJECT_DIR="${projectDir}"
cd "$PROJECT_DIR"

# Run one pipeline cycle
npx tsx daemon/src/daemon.ts --once
`;
}

// ── Tests ─────────────────────────────────────────────────────────────────

describe('agency-setup integration — file generation', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = join(tmpdir(), `agency-setup-test-${Date.now()}`);
    mkdirSync(tmpDir, { recursive: true });
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  function writeProjectFiles(config: GreatMindsConfig) {
    // .great-minds.json
    writeFileSync(join(tmpDir, '.great-minds.json'), JSON.stringify(config, null, 2));

    // STATUS.md
    writeFileSync(join(tmpDir, 'STATUS.md'), generateStatusMd(config));

    // SCOREBOARD.md
    writeFileSync(join(tmpDir, 'SCOREBOARD.md'), generateScoreboardMd(config));

    // TASKS.md
    writeFileSync(join(tmpDir, 'TASKS.md'), generateTasksMd(config));

    // crons/pipeline-runner.sh (only if schedule is set)
    const cronScript = generateCronScript(config, tmpDir);
    if (cronScript) {
      mkdirSync(join(tmpDir, 'crons'), { recursive: true });
      writeFileSync(join(tmpDir, 'crons', 'pipeline-runner.sh'), cronScript, { mode: 0o755 });
    }
  }

  it('generates .great-minds.json with correct structure', () => {
    const config = defaultConfig('sunrise-yoga');
    writeProjectFiles(config);

    const raw = JSON.parse(readFileSync(join(tmpDir, '.great-minds.json'), 'utf8'));
    expect(() => validateConfig(raw)).not.toThrow();
    expect(raw.project).toBe('sunrise-yoga');
    expect(raw.version).toBe('1.0');
    expect(raw.pipeline.autoShip).toBe(false);
  });

  it('generates STATUS.md with project name and state: idle', () => {
    const config = defaultConfig('sunrise-yoga');
    writeProjectFiles(config);

    const status = readFileSync(join(tmpDir, 'STATUS.md'), 'utf8');
    expect(status).toContain('state**: idle');
    expect(status).toContain('sunrise-yoga');
  });

  it('generates SCOREBOARD.md with project name', () => {
    const config = defaultConfig('sunrise-yoga');
    writeProjectFiles(config);

    const scoreboard = readFileSync(join(tmpDir, 'SCOREBOARD.md'), 'utf8');
    expect(scoreboard).toContain('sunrise-yoga');
    expect(scoreboard).toContain('Commits | 0');
  });

  it('generates TASKS.md with project name', () => {
    const config = defaultConfig('sunrise-yoga');
    writeProjectFiles(config);

    const tasks = readFileSync(join(tmpDir, 'TASKS.md'), 'utf8');
    expect(tasks).toContain('sunrise-yoga');
    expect(tasks).toContain('No tasks yet');
  });

  it('generates crons/pipeline-runner.sh when schedule is set', () => {
    const config: GreatMindsConfig = {
      ...defaultConfig('sunrise-yoga'),
      pipeline: { schedule: '0 * * * *', autoShip: false },
    };
    writeProjectFiles(config);

    expect(existsSync(join(tmpDir, 'crons', 'pipeline-runner.sh'))).toBe(true);
    const script = readFileSync(join(tmpDir, 'crons', 'pipeline-runner.sh'), 'utf8');
    expect(script).toContain('0 * * * *');
    expect(script).toContain('sunrise-yoga');
  });

  it('does NOT generate crons/pipeline-runner.sh when schedule is null', () => {
    const config = defaultConfig('sunrise-yoga'); // schedule: null by default
    writeProjectFiles(config);

    expect(existsSync(join(tmpDir, 'crons', 'pipeline-runner.sh'))).toBe(false);
  });

  it('STATUS.md notes manual-only pipeline when schedule is null', () => {
    const config = defaultConfig('sunrise-yoga');
    writeProjectFiles(config);

    const status = readFileSync(join(tmpDir, 'STATUS.md'), 'utf8');
    expect(status).toContain('manual only');
  });

  it('STATUS.md lists active agents', () => {
    const config: GreatMindsConfig = {
      ...defaultConfig('sunrise-yoga'),
      agents: { active: ['steve-jobs-visionary', 'margaret-hamilton-qa'], tokenBudgetPerAgent: 50000 },
    };
    writeProjectFiles(config);

    const status = readFileSync(join(tmpDir, 'STATUS.md'), 'utf8');
    expect(status).toContain('steve-jobs-visionary');
    expect(status).toContain('margaret-hamilton-qa');
  });

  it('reconfiguring (overwriting) produces correct updated files', () => {
    // First setup
    const config1 = defaultConfig('sunrise-yoga');
    writeProjectFiles(config1);

    // Reconfigure with different name + schedule
    const config2: GreatMindsConfig = {
      ...config1,
      project: 'sunset-yoga',
      pipeline: { schedule: '*/30 * * * *', autoShip: true },
    };
    writeProjectFiles(config2);

    const raw = JSON.parse(readFileSync(join(tmpDir, '.great-minds.json'), 'utf8'));
    expect(raw.project).toBe('sunset-yoga');
    expect(raw.pipeline.schedule).toBe('*/30 * * * *');
    expect(raw.pipeline.autoShip).toBe(true);

    const script = readFileSync(join(tmpDir, 'crons', 'pipeline-runner.sh'), 'utf8');
    expect(script).toContain('*/30 * * * *');
  });
});

// ── parseSchedule round-trip ──────────────────────────────────────────────

describe('agency-setup integration — schedule round-trip', () => {
  it('user says "hourly" → stored as "0 * * * *" → cron script uses "0 * * * *"', () => {
    const schedule = parseSchedule('hourly');
    expect(schedule).toBe('0 * * * *');

    const script = generateCronScript(
      { ...defaultConfig('x'), pipeline: { schedule, autoShip: false } },
      '/tmp/project'
    );
    expect(script).toContain('0 * * * *');
  });

  it('user says "manual only" → stored as null → no cron script generated', () => {
    const schedule = parseSchedule('manual only');
    expect(schedule).toBeNull();

    const script = generateCronScript(
      { ...defaultConfig('x'), pipeline: { schedule, autoShip: false } },
      '/tmp/project'
    );
    expect(script).toBeNull();
  });
});
